Use WIADBISYS
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_ObtenerMovimientosCaja')
  Drop Procedure dbo.adp_ObtenerMovimientosCaja
Go 

-- SP PARA OBTENER LOS MOVIMIENTOS DE LA CAJA DEL DÍA @FECHA_MOV
Create procedure dbo.adp_ObtenerMovimientosCaja (@FECHA_MOV datetime)
as


BEGIN TRY

	SET NOCOUNT ON
	
	SELECT  CONVERT(VARCHAR,A.FECHA,112)		'FECHA'					,
					CONVERT(VARCHAR,A.HORA,8)				'HORA'					,
					CASE B.INGRESO_SALIDA 
						WHEN 1 THEN 'INGRESO' 
						ELSE 'SALIDA' 
					END AS													'INGRESO/SALIDA',
					VALOR														'VALOR'					,
					UPPER(B.DESCRIPCION)						'MOVIMIENTO'		

	FROM MOVIMIENTOS_CAJA A
	INNER JOIN TIPOMOVIMIENTO_CAJA B ON (A.ID_TIPOMOVIMIENTO = B.ID_TIPOMOVIMIENTO)
	WHERE FECHA = @FECHA_MOV

	SET NOCOUNT OFF
	
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH	

go
