Use WIADBISYS
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_ObtenerCajaActual')
  Drop Procedure dbo.adp_ObtenerCajaActual
Go 

Create procedure dbo.adp_ObtenerCajaActual (@FECHA_MOV DATETIME)
as


BEGIN TRY

	SET NOCOUNT ON
	
	SELECT	CAJA_INICIAL	AS 'INICIAL', 
					CAJA_FINAL		AS 'FINAL',
					IMPORTE_TOTAL AS 'TOTAL'
	FROM CAJA
	WHERE FECHA = @FECHA_MOV

	SET NOCOUNT OFF
	
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH
 
go
