Use WIADBISYS
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_modificarCajaInicial')
  Drop Procedure adp_modificarCajaInicial
Go 

-- SP QUE REGISTRAN LOS MOVIMIENTOS PARAMETRIZADOS DE LA CAJA
Create procedure adp_modificarCajaInicial (@Fecha Datetime,	@Valor NUMERIC(10,2))
as

BEGIN TRY
  SET NOCOUNT ON
  PRINT 'INICIO ACTUALIZACIÓN'
  
	UPDATE MOVIMIENTOS_CAJA
	SET VALOR = @Valor
	WHERE FECHA = @FECHA
		AND ID_TipoMovimiento = 1

  PRINT 'FIN ACTUALIZACIÓN OK'
  SET NOCOUNT OFF
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH
go
