Use WIADBISYS
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_actualizar_MovCaja')
  Drop Procedure adp_actualizar_MovCaja
Go 

-- SP QUE BUSCA RUBROS DE ACUERDO A LOS PARAMETROS QUE RECIBA.

Create procedure adp_actualizar_MovCaja (	@ID_MOVIMIENTO NUMERIC(30), 
																					@VALOR NUMERIC(10,2), 
																					@FECHA DATETIME, 
																					@HORA VARCHAR(8))
as

BEGIN TRY
  SET NOCOUNT ON
  PRINT 'INICIO ACTUALIZACIÓN'
  
  UPDATE A
  SET VALOR = @VALOR,
			FECHA = @FECHA,
			HORA  = @HORA
  FROM MOVIMIENTOS_CAJA A
  WHERE ID_MOVIMIENTO = @ID_MOVIMIENTO
							
  PRINT 'FIN ACTUALIZACIÓN OK'
  SET NOCOUNT OFF
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH
go
