Use WIADBISYS
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_actualizar_TipoMovCaja')
  Drop Procedure adp_actualizar_TipoMovCaja
Go 

-- SP QUE BUSCA RUBROS DE ACUERDO A LOS PARAMETROS QUE RECIBA.

Create procedure adp_actualizar_TipoMovCaja (@ID_TIPOMOVIMIENTO NUMERIC(30),
																						 @DESCRIPCION				VARCHAR(255),
																						 @INGRESO_SALIDA		NUMERIC(1),
																						 @FECHA_MODIF				DATETIME,
																						 @LOGIN_MODIF				VARCHAR(255))
as

BEGIN TRY
  SET NOCOUNT ON
  PRINT 'INICIO ACTUALIZACIÓN'
  
	UPDATE A
	SET A.DESCRIPCION			= @DESCRIPCION,
			A.INGRESO_SALIDA	= @INGRESO_SALIDA,
			A.FECHA_MODIF			= @FECHA_MODIF,
			A.LOGIN_MODIF			=	@LOGIN_MODIF,
			A.TERM_MODIF			= HOST_NAME()
	FROM TIPOMOVIMIENTO_CAJA A
	WHERE A.ID_TipoMovimiento = @ID_TIPOMOVIMIENTO
							
  PRINT 'FIN ACTUALIZACIÓN OK'
  SET NOCOUNT OFF
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH
go
