Use WIADBISYS
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_eliminarMovCaja')
  Drop Procedure adp_eliminarMovCaja
Go 

-- SP QUE SI SE ELIMINARON TODOS LOS PROVEEDORES, REINICIA EL CAMPO IDENTITY.

Create procedure dbo.adp_eliminarMovCaja (@ID_MovimientoCaja AS NUMERIC(30))
as


BEGIN TRY
  SET NOCOUNT ON
  PRINT 'INICIO ACTUALIZACIÓN'
  
	DELETE A
	FROM MOVIMIENTOS_CAJA A
	WHERE A.ID_Movimiento = @ID_MovimientoCaja
	
  PRINT 'FIN ACTUALIZACIÓN OK'
  SET NOCOUNT OFF
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH
go
