Use WIADBISYS
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_ObtenerTiposMovsCaja')
  Drop Procedure adp_ObtenerTiposMovsCaja
Go 

-- SP QUE INSERTA UN NUEVO PROVEEDOR.
Create procedure adp_ObtenerTiposMovsCaja 
as


BEGIN TRY

	SET NOCOUNT ON

	SELECT	ID_TIPOMOVIMIENTO	'CODIGO',
					UPPER(DESCRIPCION) 'TIPO MOVIMIENTO',
					CASE INGRESO_SALIDA 
						WHEN 1 THEN 'INGRESO' 
						ELSE 'SALIDA' 
					END AS	'INGRESO/SALIDA'
	FROM TIPOMOVIMIENTO_CAJA

	SET NOCOUNT OFF
	
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH
go
