Use WIADBISYS
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_ObtenerTiposMovsCaja')
  Drop Procedure adp_ObtenerTiposMovsCaja
Go 

-- SP QUE INSERTA UN NUEVO PROVEEDOR.
Create procedure adp_ObtenerTiposMovsCaja 
as


BEGIN TRY

	SET NOCOUNT ON

	SELECT	ID_TIPOMOVIMIENTO	'CODIGO',
					UPPER(DESCRIPCION) 'MOVIMIENTO',
					CASE INGRESO_SALIDA 
				  	WHEN 1 THEN 'INGRESO' 
						ELSE 'SALIDA' 
					END AS	'INGRESO/SALIDA',
					CONVERT(VARCHAR,fecha_modif,112) 'FECHA_MODIF',
					UPPER(login_modif) 'LOGIN_MODIF',
					UPPER(term_modif) 'TERM_MODIF'
	FROM TIPOMOVIMIENTO_CAJA
	WHERE 1 = 1
		AND ID_TIPOMOVIMIENTO != 0
		AND ESTADO = 1

	SET NOCOUNT OFF
	
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH
go
