Use WIADBISYS
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_VerificoExistenciaMovCaja')
  Drop Procedure adp_VerificoExistenciaMovCaja
Go 

-- SP QUE BUSCA RUBROS DE ACUERDO A LOS PARAMETROS QUE RECIBA.

Create procedure dbo.adp_VerificoExistenciaMovCaja (@FECHA_MOV DATETIME)
as

BEGIN TRY
  SET NOCOUNT ON
  PRINT 'INICIO ACTUALIZACIÓN'
  
  SELECT 1 
  FROM MOVIMIENTOS_CAJA 
  WHERE Fecha = @FECHA_MOV
							
  PRINT 'FIN ACTUALIZACIÓN OK'
  SET NOCOUNT OFF
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH
go
