Use WIADBISYS
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_actualizacionMasiva_Articulos')
  Drop Procedure adp_actualizacionMasiva_Articulos
Go 

-- SP QUE ACTUALIZA EL IMPORTE DE LOS ARTICULOS POR PORCENTAJE O POR PRECIO
Create procedure adp_actualizacionMasiva_Articulos (@RUBRO AS INT,
																										@SUMA_RESTA AS CHAR(1),
																										@SINO_ACTPORCENTAJE AS NUMERIC(1), 
																										@PORCENTAJE AS NUMERIC(2),
																										@VALOR AS NUMERIC(4),
																										@LOGIN_MODIF AS VARCHAR(255))
as


BEGIN TRY

	SET NOCOUNT ON
	
	
	IF @SINO_ACTPORCENTAJE = 1 --ACTUALIZACIÓN POR PORCENTAJE
		BEGIN
			IF @SUMA_RESTA = '+'
				BEGIN
					UPDATE A
					SET	A.PRECIO_VENTA = A.PRECIO_VENTA + (A.PRECIO_VENTA * @PORCENTAJE),
							A.FECHA_MODIF = GETDATE(),
							A.LOGIN_MODIF = @LOGIN_MODIF,
							A.TERM_MODIF = HOST_NAME()
					FROM ARTICULOS A
					WHERE A.RUBRO = @RUBRO
				END ELSE BEGIN
					UPDATE A
					SET	A.PRECIO_VENTA = A.PRECIO_VENTA - (A.PRECIO_VENTA * @PORCENTAJE),
							A.FECHA_MODIF = GETDATE(),
							A.LOGIN_MODIF = @LOGIN_MODIF,
							A.TERM_MODIF = HOST_NAME()
					FROM ARTICULOS A	
					WHERE A.RUBRO = @RUBRO			
				END
		END ELSE BEGIN --ACTUALIZACIÓN POR PRECIO
			IF @SUMA_RESTA = '+'
				BEGIN
					UPDATE A
					SET	A.PRECIO_VENTA = A.PRECIO_VENTA + @VALOR,
							A.FECHA_MODIF = GETDATE(),
							A.LOGIN_MODIF = @LOGIN_MODIF,
							A.TERM_MODIF = HOST_NAME()
					FROM ARTICULOS A
					WHERE A.RUBRO = @RUBRO
				END ELSE BEGIN
					UPDATE A
					SET	A.PRECIO_VENTA = A.PRECIO_VENTA - @VALOR,
							A.FECHA_MODIF = GETDATE(),
							A.LOGIN_MODIF = @LOGIN_MODIF,
							A.TERM_MODIF = HOST_NAME()
					FROM ARTICULOS A
					WHERE A.RUBRO = @RUBRO
				END
		END

	SET NOCOUNT OFF
	
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH
go
