Use WIAdbisys
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_obtener_articulos')
  Drop Procedure adp_obtener_articulos
Go 

-- SP PARA OBTENER LOS DIFERENTES ARTICULOS.
Create procedure dbo.adp_obtener_articulos (@Id_Articulo As NUMERIC(20) = NULL)
as

BEGIN TRY

	SET NOCOUNT ON
	
	SELECT A.ID_ARTICULO				AS 'CÓDIGO',
				 UPPER(A.DESCRIPCION)	AS 'DESCRIPCIÓN',
				 A.PRECIO_VENTA				AS 'PRECIO_VENTA',
				 UPPER(B.DESCRIPCION) AS 'RUBRO',
				 CONVERT(VARCHAR,A.FECHA_MODIF,120) AS 'FECHA_MODIF',
				 UPPER(A.LOGIN_MODIF) AS 'LOGIN_MODIF',
				 UPPER(A.TERM_MODIF)  AS 'TERM_MODIF'

	FROM ARTICULOS A
		INNER JOIN RUBROS B ON (A.RUBRO = B.ID_RUBRO)
		WHERE A.ESTADO = 1
		  AND A.ID_Articulo = ISNULL(@Id_Articulo, A.ID_Articulo)

	SET NOCOUNT OFF
	
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH	

go
