Use WIAdbisys
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_obtenerArticulosVenta_Temporal')
  Drop Procedure adp_obtenerArticulosVenta_Temporal
Go 

-- SP PARA OBTENER ARTICULOS DE LA VENTA EN LA TABLA TEMPORAL (TABLA QUE TENDRA DATOS HASTA EL MOMENTO DE CONFIRMAR LA VENTA)
Create procedure dbo.adp_obtenerArticulosVenta_Temporal 
as

BEGIN TRY

	SET NOCOUNT ON
	
	SELECT C.ID_Item_Venta      AS 'ID',
	       A.ID_ARTICULO				AS 'CÓDIGO',
				 UPPER(A.DESCRIPCION)	AS 'DESCRIPCIÓN',
				 C.Cantidad           AS 'CANTIDAD',
				 CASE WHEN C.ID_Articulo = 1 
								THEN C.IMPORTE
								ELSE A.PRECIO_VENTA	
				 END AS 'PRECIO_UNIDAD',
				 CASE WHEN C.ID_Articulo = 1
								THEN C.IMPORTE
								ELSE A.PRECIO_VENTA	
				 END * C.CANTIDAD AS 'PRECIO_TOTAL',
				 UPPER(B.DESCRIPCION) AS 'RUBRO',
				 CONVERT(VARCHAR,A.FECHA_MODIF,120) AS 'FECHA_MODIF',
				 UPPER(A.LOGIN_MODIF) AS 'LOGIN_MODIF',
				 UPPER(A.TERM_MODIF)  AS 'TERM_MODIF'

	FROM ARTICULOS A
		INNER JOIN RUBROS B ON (A.RUBRO = B.ID_RUBRO)
		INNER JOIN TMP_ARTICULOS_VENTAS C ON (A.ID_Articulo = C.ID_Articulo)
		WHERE A.ESTADO = 1

  
	SET NOCOUNT OFF
	
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH	

go
