Use WIAdbisys
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_ActualizarMovimientosCaja_Venta')
  Drop Procedure adp_ActualizarMovimientosCaja_Venta
Go 

-- SP QUE ACTUALIZA EL MOVIMIENTO DE LA CAJA DE VENTAS.

Create procedure dbo.adp_ActualizarMovimientosCaja_Venta (@FECHA DATETIME)
as

BEGIN TRY
  SET NOCOUNT ON
  PRINT 'INICIO ACTUALIZACIÓN'
  
  DECLARE @IMPORTE_VENTAS NUMERIC(20,2)
	DECLARE @HORA VARCHAR(8)
  
  SELECT @IMPORTE_VENTAS = isnull(SUM(IMPORTE),'0.00')
  FROM VENTAS 
  WHERE 1 = 1
    AND Fecha_Venta = @FECHA 
    AND ESTADO = 1
  
  SET @HORA = SUBSTRING(CONVERT(VARCHAR,GETDATE(),114),1,8)
  
	UPDATE MOVIMIENTOS_CAJA 
		SET VALOR = @IMPORTE_VENTAS,
				HORA	= @HORA
		WHERE 1 = 1
		  AND ID_TIPOMOVIMIENTO = 3 
		  AND FECHA = @FECHA
							
  PRINT 'FIN ACTUALIZACIÓN OK'
  SET NOCOUNT OFF
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH
go
