Use WIAdbisys
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_obtener_ganancia')
  Drop Procedure adp_obtener_ganancia
Go 

-- SP QUE OBTIENE LA GANANCIA ENTRE LAS FECHAS RECIBIDAS COMO PARAMETRO.

Create procedure adp_obtener_ganancia @FECHA_DESDE DATETIME,
																			@FECHA_HASTA DATETIME
as

BEGIN TRY
  SET NOCOUNT ON
  PRINT 'INICIO ACTUALIZACIÓN'
  
  SELECT (ISNULL(SUM(B.PRECIO_VENTA * B.CANTIDAD) - SUM(CASE WHEN B.ID_ARTICULO = 1 THEN B.PRECIO_VENTA
																														 ELSE B.PRECIO_COMPRA
																												END * B.CANTIDAD),'0.00')) AS GANANCIA
		FROM VENTAS A 
		INNER JOIN ARTICULOS_VENTAS B ON (A.ID_VENTA = B.ID_VENTA)
		INNER JOIN ARTICULOS C ON (C.ID_ARTICULO = B.ID_ARTICULO)
	WHERE 1=1 
		AND A.FECHA_VENTA BETWEEN @FECHA_DESDE AND @FECHA_HASTA
		AND A.ESTADO = 1

		
	PRINT 'FIN ACTUALIZACIÓN OK'
  SET NOCOUNT OFF
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH
go
