Use WIAdbisys
Go 
If Exists ( Select 1 From SysObjects Where Name = 'adp_cierre_parcial')
  Drop Procedure adp_cierre_parcial
Go 

-- SP QUE OBTIENE EL CIERRE PARCIAL DE LA CAJA HASTA EL MOMENTO.

Create procedure adp_cierre_parcial @FECHA DATETIME
as

BEGIN TRY
  SET NOCOUNT ON
  PRINT 'INICIO ACTUALIZACIÓN'
  
  DECLARE @INGRESO NUMERIC(30,2)
  DECLARE @SALIDA NUMERIC(30,2)
	
	SELECT @INGRESO = SUM(VALOR) FROM MOVIMIENTOS_CAJA A
		INNER JOIN TIPOMOVIMIENTO_CAJA B ON (A.ID_TIPOMOVIMIENTO = B.ID_TIPOMOVIMIENTO)
	WHERE B.INGRESO_SALIDA = 1 AND A.FECHA = @FECHA AND B.ESTADO = 1
	
	SELECT @SALIDA = SUM(VALOR) FROM MOVIMIENTOS_CAJA A
		INNER JOIN TIPOMOVIMIENTO_CAJA B ON (A.ID_TIPOMOVIMIENTO = B.ID_TIPOMOVIMIENTO)
	WHERE B.INGRESO_SALIDA = 0 AND A.FECHA = @FECHA AND B.ESTADO = 1
	
	SELECT @INGRESO - @SALIDA AS CIERRE_PARCIAL
		
	PRINT 'FIN ACTUALIZACIÓN OK'
  SET NOCOUNT OFF
END TRY

BEGIN CATCH
  SET NOCOUNT OFF
  PRINT 'ACTUALIZACION CANCELADA POR ERROR'
  SELECT ERROR_NUMBER()     'ERROR_NUMBER' , 
         ERROR_MESSAGE()    'ERROR_MESSAGE', 
         ERROR_LINE()       'ERROR_LINE', 
         ERROR_PROCEDURE()  'ERROR_PROCEDURE', 
         ERROR_SEVERITY ()  'ERROR_SEVERITY',   
         ERROR_STATE()      'ERROR_STATE'
END CATCH
go
